sudo: false
language: python
python:
- '3.6'
services:
- docker
notifications:
  email:
    on_failure: always
    on_success: never
jobs:
  include:
  - stage: build and push docker image
    if: tag IS present
    script:
    - echo $TRAVIS_TAG
    - echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
    - docker build -t kaecloud/cli:latest .
    - docker tag kaecloud/cli:latest kaecloud/cli:$TRAVIS_TAG
    - docker images
    - docker push kaecloud/cli:$TRAVIS_TAG
    - docker push kaecloud/cli:latest
    deploy:
      provider: pypi
      skip_existing: true
      on:
        tags: true
        repo: kaecloud/cli
      password:
        secure: QEsBPnPpJyiAQu144lMHVuHx/3E3aOj9FoGwyD2bt/XPtOuiZ7Gj7vCDeb5upeFnLYLwTE+Znv+KVK+f9+Hmh5A8mbgMjADkqroonxG3NAUyFEKDcHvSnn328fItdprDx+EQVadhz8ImWfw5jvOF7f3yaOZ3JBx/jsjbxpkm2xegzeYk5SNNwIfbxI9W14khuzu0hgoiuRmg5JIGOC8owNzbUsBvvbIT7ezy92HqkQEYKhmTg1H+apuW5yie6ZCk5I7mV48Yi02K9gRd50PNDTcxSY2DvL9pYx49zypTapDgBfC1ysPsif2yOSEOqbXY7ucbQt3q+jF8rkx8sefBDcJojeBBfNu6mLXi6sNBplfnXRpOyrxJ74JJemUNPNUhCpBEjnNCVNfTcpI/y0T829r4exV1QmZ0HJjtoSBaSCqMBRIfG0+eBl6OwEt9sk8M7m29OF0rQMHWrSPeWhWloXkM182jdCZskgNBksGcDylVkQMHHE43O9q9qaAAICwrn6x9h56oJ4rkuCE4n3Ec88X3JYs6QWQwLWzPPvZXLRBuyO7QrxaEUFnPtL6PeCce56YaBT35uF33/WSyPXLCLWn4iGqDYOYZwBsTGK4hvCP1TQwUgkNL34AZbqhAC+H8rSq+Y+MGWexa123uuE96uSk38kP55yxTpxxz3+S7Aw4=
      user:
        secure: RjumCdnBfJRjG3jRyQNbn/xixnfDL34ZiWp4U1m8D885QExiP6faVcSPlo2530XEiWBrEj6OHKB7TgRtGw+75wn1yp1PV6HFiQwQ8DIT+RG6dEX/induUC+w08S6u6sMJGZjBsECbiKIwLsvLifnei0bJ1E1F3LjBrINxotNuKxKGrcWZgF2O78u4gGJeeqp8EYWO44P6Tci6bk1c+oE/vIcjw8phzQXn/70mgl3C8YgNet87XOvkOoD2L+3bBNYxBVZ8HIcbEdjDLcfBChJKxFbwxJWYPiIiPP/2R5L9Jg8PqNDWlPi4w5ru9chhpIE1M8FuLBCXpw2zqn7Ld08aZ+jpG7rRCIRWaTIxHW03078P+fdkPTd1GuaGeanEa9mayuyL3xTq9499tK9z5KHoGGH0lGf7M059mLcwE55Ljhrw4LvuBIMHAhsjYZWx5bpMDGFaFGPY3mwswe8vtKc0MmiCCDfTOqI1cBj8DqPp5qqq+9oAbV2bcofQS9sRYSuh+WLC21fyVae/DBp7jPaoCMI1Y3QZzt8tzgKGPdP9wET2DmHzm/Q9QjX9JFK2FV1qYDn2ibSYnnFk0JELarjhExAcfNpwzqo2uszI/45bnuiuhGuYF/4pGDY5TK0Spy2Jsp6pYJsTJZw2f6t35tZqmCIYGRk0tBpgUa0aSnofAU=
env:
  global:
  - secure: drTT0GlTd6CB3jdBGhn+wcyEq0FjQuuhOHYlWi98maRWoFfpZuSnIvWTWMiy7jKzM6EKb3Yi51n4U9PQU9fysVUGA6USZsCYZeF6n7x9ReTNFAuIn8ehyVdkHYGDh6XOlwIUN+9S7y4aK35vl8eGuHoKa4a8Ta2IdmzIuVEBbJlTCm1Alg36287twwcXMJXpx5P5VNnJuBQ7Uaalvsq8kV/tg+YQlqkU3Sh0oLaD1Jw9wWq8nhlvitl6Y6mNgz8cYYEgokUIMYoNT62OVZ/9sLPGPSxl5R8KcdTNIji9+5rEbtVgQ6l/erB2IQvxOcfCkfJr0YtD7rFGTz2w9H69yPyUUuNKEISkJ3IhLAWaRceEGkUh6YESJDtBfPOmxwDNvzQzlKcxrM+Sy6NCMfCQgUQORfadYaNYHDk+VcRJWpPWDHQYYethOoQS7TSdKSrLSFGTe9VAv9d+SX2VYOtgiDhAW5R/KjOGsxELIRwMNsrivYCXyyDKmyGDSLnuXf+1dreUU5XRLuhprbrblXsNPe8sNB7t8aznwQf9Rt5w1j4MGlGlObQulMtqyRANvMQDU+8ER6uiYOI6s/FuybNdOEkt9xLHlw6kGUgBM446qncxFA310hfbdQyxGDjpmUUbaZgbya+rLXBY/3gOjeU2UvJkieEp99yHF+piSqvc8B0=
  - secure: DNv8+dIYDf+t4zf5qxBQtbelX9UVgeZpzr3xT2D5tB3LakxYcZiqpIsQOj1MEMkSnYSC5QyBR+4GIPccoMQfOcDXnoGCVpejUr1ywzXyR1RsbiB1T9S7QVsMQDlvs25PHLgzko5IahFBwd4nQYhmaVQ6ksfU5WMR97VzJ2vDJRR7Iw4Gx9MnGNHiKQBEAt62hlSZHZwEFiVoTOQho+qySdpdnolJvYFaTnY5oQUtdH1oN9moDZTD28pMM7M26Qq4lF38M985hzG3rzwan1S6lA1/kMTpxbU1ePXA1r3/6WfRD+tmRj062eqS4TdtyAVsY+jqlgHfmoAgpv93KrHca1rXPQs/G3PsX211dwCuJx4vfHGFMg6PJTfucLCYIDq9z6xGNrwE91fGcfPM0Sk7fpkdUpZnwnwLwHQaxWrUcRg6tEIbrX/UVUM67N0QV+Pf7inM76xV4EO+oZVdHlCFoA3aCV2L3+/9+p86nn2xovCCRDiygCASjP6aSgKvm8muLeUhI7aYCujnnfS1v0egyls829ovN9pSm4Ocec67dH4HQju5ZZSrpnM03/9CCR13CgQQVpTzg7M3IVWuS0qOx/26x/5TBvVEocZEW0NApZKuHAwxfjVBjscfSDp3OX2Ikk77ib/0p7K1gkt5GnOU32I9an1i8nHO6jYPdJMBJmw=
